<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PingLogger</title>
<link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link href="//github.hubspot.com/sortable/css/sortable-theme-bootstrap.css" rel="stylesheet">
<script src="//cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js"></script>
<script>jQuery = Zepto</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script src="//github.hubspot.com/sortable/js/sortable.min.js"></script>
</head>
<body>

<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <a class="navbar-brand" href=".">PingLogger</a>
  </div>
</div>

<div class="container">
<form action="." onchange="this.submit()">

<label for="source">Source</label>
<select id="source" name="source">
    <option value="">Select...</option>
<?php foreach (array_keys($sourcesHosts) as $sourceItem): ?>
    <option value="<?php print($sourceItem); ?>"<?php if (@$params->source === $sourceItem): ?>selected<?php endif; ?>><?php print($sourceItem); ?></option>
<?php endforeach; ?>
</select>

<label for="host">Host</label>
<select id="host" name="host">
    <option value="">Select...</option>
<?php if (@$params->source): ?>
<?php foreach (@$sourcesHosts[$params->source] as $hostItem): ?>
    <option value="<?php print($hostItem); ?>"<?php if (@$params->host === $hostItem): ?>selected<?php endif; ?>><?php print($hostItem); ?></option>
<?php endforeach; ?>
<?php endif; ?>
</select>

</form>
</div>

<?php if (@$data): ?>
<div class="container">
<table class="table sortable-theme-bootstrap" style="width:100%" data-sortable>
    <thead>
        <tr>
<?php foreach ($fields as $field => $info): ?>
            <th<?php if (@$info['default_sort']): ?> data-sorted="true" data-sorted-direction="descending"<?php endif; ?>><?php print($info['title']); ?></th>
<?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
<?php foreach ($data as $row): ?>
        <tr>
<?php foreach ($fields as $field => $info): ?>
            <td><?php print($row->{$field}); ?></td>
<?php endforeach; ?>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>
</div>
<?php endif; ?>

</body>
</html>