<!DOCTYPE HTML>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>PingLogger</title>
<link href="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
<link href="//github.hubspot.com/sortable/css/sortable-theme-bootstrap.css" rel="stylesheet">
<script src="//cdnjs.cloudflare.com/ajax/libs/zepto/1.2.0/zepto.min.js"></script>
<script>jQuery = Zepto</script>
<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script src="//github.hubspot.com/sortable/js/sortable.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.bundle.min.js"></script>
</head>
<body>

<div class="navbar navbar-inverse" role="navigation">
  <div class="container">
    <a class="navbar-brand" href=".">PingLogger</a>
  </div>
</div>

<div class="container">
<form action="." onchange="this.submit()">

<span class="pull-left" style="margin-right:1em;">
<label for="source">Source</label><br>
<select id="source" name="source">
    <option value="">Select...</option>
<?php foreach (array_keys($sourcesHosts) as $sourceItem): ?>
    <option value="<?php print($sourceItem); ?>"<?php if (@$params->source === $sourceItem): ?> selected<?php endif; ?>><?php print($sourceItem); ?></option>
<?php endforeach; ?>
</select>
</span>

<span class="pull-left" style="margin-right:1em;">
<label for="host">Host</label><br>
<select id="host" name="host">
    <option value="">Select...</option>
<?php if (@$params->source): ?>
<?php foreach (@$sourcesHosts[$params->source] as $hostItem): ?>
    <option value="<?php print($hostItem); ?>"<?php if (@$params->host === $hostItem): ?> selected<?php endif; ?>><?php print($hostItem); ?></option>
<?php endforeach; ?>
<?php endif; ?>
</select>
</span>

<?php if (@$params->source && @$params->host): ?>
<span class="pull-left" style="margin-right:1em;">
<label for="range">Range</label><br>
<select id="range" name="range">
<?php foreach ($ranges as $rangeFrequency => $rangeTitle): ?>
    <option value="<?php print($rangeFrequency); ?>"<?php if ((int)$range === $rangeFrequency): ?> selected<?php endif; ?>><?php print($rangeTitle); ?></option>
<?php endforeach; ?>
</select>
</span>

<span class="pull-left" style="line-height:4em;">
<input type="hidden" name="mode" value="<?php print($mode); ?>">
<input type="submit" name="mode" value="Chart" class="btn btn-default<?php if ('chart' === $mode): ?> active<?php endif; ?>" style="margin-right:1em;">
<input type="submit" name="mode" value="Table" class="btn btn-default<?php if ('table' === $mode): ?> active<?php endif; ?>">
</span>
<?php endif; ?>

</form>
</div>

<?php if (@$data): ?>
<div class="container">

<?php if ('chart' === $mode): ?>

<canvas id="chart" width="300" height="120"></canvas>

<script>
var data = <?php print($data); ?>;
</script>

<script>
var ctx = document.getElementById('chart');
var chart = new Chart(ctx, {
    type: 'line',
    data: window.data,
    options: {
        animation: false,
        scales: {
            xAxes: [{
                type: 'time',
                time: {
                    displayFormats: {
                        minute: 'HH:mm',
                        hour: 'YYYY-MM-DD HH:mm',
                    },
                },
            }],
            yAxes: [{
                position: 'left',
                id: 'left',
            }, {
                position: 'right',
                id: 'right',
            }]
        },
    },
});
</script>

<?php else: ?>

<table class="table sortable-theme-bootstrap" style="width:100%" data-sortable>
    <thead>
        <tr>
<?php foreach ($fields as $field => $info): ?>
            <th<?php if (@$info['default_sort']): ?> data-sorted="true" data-sorted-direction="descending"<?php endif; ?>><?php print($info['title']); ?></th>
<?php endforeach; ?>
        </tr>
    </thead>
    <tbody>
<?php foreach ($data as $row): ?>
        <tr>
<?php foreach ($fields as $field => $info): ?>
            <td><?php print($row->{$field}); ?></td>
<?php endforeach; ?>
        </tr>
<?php endforeach; ?>
    </tbody>
</table>

<?php endif; ?>

</div>
<?php endif; ?>

</body>
</html>